services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      - GF_SECURITY_ADMIN_USER=${NACOS_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${NACOS_PASSWORD}

  mcp-router:
    image: nacos/nacos-mcp-router:latest
    container_name: nacos-mcp-router
    # for host networking (same as --network host)
    network_mode: host
    # map your env-vars through Compose
    environment:
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAME=${NACOS_USERNAME}
      - NACOS_PASSWORD=${NACOS_PASSWORD}
      - TRANSPORT_TYPE=${TRANSPORT_TYPE}
    depends_on:
      - nacos
    restart: on-failure
